stages:
  - deploy

variables:
  DEPLOY_PATH: /var/docker/gpcentre-net
  WWW_PATH: /var/www/gpcentre-net

before_script:
  - echo "ENV=production" >> .env
  - echo "VAR_ROOT=/var" >> .env
  - echo "COMPOSE_PROJECT_NAME=gpcentre-net" >> .env

deploy:www:
  stage: deploy
  # variables:
  #   CI_DEBUG_TRACE: "true"
  script:
    - rm -rf "$WWW_PATH"
    - cp -R src/ "$WWW_PATH"

deploy:docker:
  stage: deploy
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - rm -rf "$DEPLOY_PATH"
    - cp -R "$CI_PROJECT_DIR" "$DEPLOY_PATH"
    - cd "$DEPLOY_PATH"
    - docker-compose up -d

after_script:
  - cd "$DEPLOY_PATH"
  - rm -rf .git*
