image: alpine
stages:
  - review
  - production

variables:
  APPS_DOMAIN: gpcentre.net
  CI_DEBUG_TRACE: "true"

review:
  stage: review
  image: richarvey/nginx-php-fpm:latest
  variables:
    DEPLOY_ROOT: /var/www/containers/$CI_BUILD_REF_SLUG-gpcentre-net
    GIT_EMAIL: gp@gpcentre.net
    GIT_NAME: "Philip G"
    GIT_USERNAME: guice
    GIT_REPO: gitlab.com/gpcentre/gpcentre-net.git
    GIT_PERSONAL_TOKEN: yog3w9qyrtMw5688t8Ps
    VIRTUAL_HOST: $CI_BUILD_REF_SLUG.gpcentre.net
    COMPOSE_PROJECT_NAME: gpcentre-net
    DOMAIN: www.gpcentre.net
    WEBROOT: /var/www/html/public
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_SLUG.$APPS_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  tags:
    - docker

stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
    DEPLOY_ROOT: /var/www/containers/$CI_BUILD_REF_SLUG-gpcentre-net
  script:
    # Removing any existing.env
    - cd $DEPLOY_ROOT
    - echo COMPOSE_PROJECT_NAME=$CI_BUILD_REF_SLUG > .env
    - echo VIRTUAL_HOST=$CI_BUILD_REF_SLUG.gpcentre.net >> .env
    - docker-compose -p $CI_BUILD_REF_SLUG down --remove-orphans
    - rm -rf $DEPLOY_ROOT
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  tags:
    - review-apps
    - shell

production:
  stage: production
  variables:
    DEPLOY_ROOT: /var/www/containers/gpcentre-net
  script:
    - mkdir -p $DEPLOY_ROOT
    - cd $DEPLOY_ROOT
    - cp -p /etc/docker/envs/gpcentre-net .env
    - docker-compose -p gpcentre.net up -d --remove-orphans
  tags:
    - shell
    - sfo2
  when: manual
  only:
    - master
