image: alpine
stages:
  - review
  - production

variables:
  APPS_DOMAIN: gpcentre.net
#  CI_DEBUG_TRACE: "true"

review:
  stage: review
  image: richarvey/nginx-php-fpm:latest
  variables:
    GIT_EMAIL: gp@gpcentre.net
    GIT_NAME: "Philip G"
    COMPOSE_PROJECT_NAME: gpcentre-net
    DOMAIN: www.gpcentre.net
    WEBROOT: /var/www/html/public
    GIT_REPO: $CI_REPOSITORY_URL
    GIT_USERNAME: $CI_REGISTRY_USER
    GIT_PERSONAL_TOKEN: $CI_REGISTRY_PASSWORD
    GIT_BRANCH: $CI_BUILD_REF_NAME
    VIRTUAL_HOST: $CI_BUILD_REF_SLUG.gpcentre.net
  script:
    - echo "Deploying Review App to http://$CI_BUILD_REF_SLUG.$APPS_DOMAIN"
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_SLUG.$APPS_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  tags:
    - docker

stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Removing review/$CI_BUILD_REF_NAME Environment"
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  tags:
    - review-apps
    - shell

production:
  stage: production
  variables:
    DEPLOY_ROOT: /var/www/containers/gpcentre-net
  script:
    - mkdir -p $DEPLOY_ROOT
    - cd $DEPLOY_ROOT
    - cp -p /etc/docker/envs/gpcentre-net .env
    - docker-compose -p gpcentre.net up -d --remove-orphans
  tags:
    - shell
    - sfo2
  when: manual
  only:
    - master
