image: alpine
stages:
  - review
  - production

variables:
  GIT_EMAIL: gp@gpcentre.net
  GIT_NAME: "Philip G"
  DOMAIN: www.gpcentre.net
  WEBROOT: /var/www/html/public
  APPS_DOMAIN: gpcentre.net
#  CI_DEBUG_TRACE: "true"

review:
  stage: review
  image: richarvey/nginx-php-fpm:latest
  variables:
    COMPOSE_PROJECT_NAME: $CI_BUILD_REF_SLUG
  script:
    - echo "GIT_BRANCH=$CI_BUILD_REF_NAME" > .env
    - echo "VIRTUAL_HOST=$CI_BUILD_REF_SLUG.gpcentre.net" >> .env
    - echo "Deploying Review App to $CI_BUILD_REF_SLUG.gpcentre.net"
    - docker-compose -p $CI_BUILD_REF_SLUG up -d
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_SLUG.$APPS_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  tags:
    - shell
    - sfo2

stop_review:
  stage: review
  variables:
    COMPOSE_PROJECT_NAME: $CI_BUILD_REF_SLUG
    GIT_STRATEGY: none
  script:
    - docker-compose -p $CI_BUILD_REF_SLUG down --remove-orphans
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  tags:
    - shell
    - sfo2
  except:
    - master

production:
  stage: production
  variables:
    GIT_REPO: $CI_REPOSITORY_URL
    GIT_USERNAME: $CI_REGISTRY_USER
    GIT_PERSONAL_TOKEN: $CI_REGISTRY_PASSWORD
    GIT_BRANCH: $CI_BUILD_REF_NAME
    DEPLOY_ROOT: /var/www/containers/gpcentre-net
  script:
    - docker-compose -p gpcentre.net up -d --remove-orphans
  tags:
    - shell
    - sfo2
  when: manual
  only:
    - master
