image: alpine
stages:
  - review
  - production

variables:
  APPS_DOMAIN: gpcentre.net
#  CI_DEBUG_TRACE: "true"

review:
  stage: review
  image: richarvey/nginx-php-fpm:latest
  script:
    - echo COMPOSE_PROJECT_NAME=$CI_BUILD_REF_SLUG > .env
    - echo VIRTUAL_HOST=$CI_BUILD_REF_SLUG.gpcentre.net >> .env
    - echo GIT_BRANCH="$CI_BUILD_REF_NAME" >> .env
    - docker-compose up -d --remove-orphans
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_SLUG.$APPS_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  tags:
    - shell
    - sfo2

stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - docker-compose down --remove-orphans
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  tags:
    - shell
    - sfo2
  except:
    - master

production:
  stage: production
  script:
    - docker-compose up -d --remove-orphans
  tags:
    - shell
    - sfo2
  when: manual
  only:
    - master
