image: alpine
stages:
  - deploy-www
  - deploy-container

variables:
  DEPLOY_PATH: /var/docker/gpcentre-net
  WWW_PATH: /var/www/gpcentre-net

deploy:www:
  stage: deploy-www
  # variables:
  #   CI_DEBUG_TRACE: "true"
  tags:
    - shell
    - sfo2
  script:
    - rsync -av --delete src/ "$WWW_PATH"

deploy:container:
  stage: deploy-container
  # variables:
  #   CI_DEBUG_TRACE: "true"
  tags:
    - shell
    - sfo2
  script:
    - docker-compose down --remove-orphans
    - rm -rf "$DEPLOY_PATH"
    - cp -R "$CI_PROJECT_DIR" "$DEPLOY_PATH"
    - cd "$DEPLOY_PATH"
    - docker-compose up -d
    - rm -rf .git*
