image: alpine
stages:
  - review
  - production

variables:
 CI_DEBUG_TRACE: "true"

variables:
  APPS_DOMAIN: gpcentre.net

review:
  stage: review
  variables:
    DEPLOY_ROOT: /var/www/containers/$CI_BUILD_REF_SLUG-gpcentre-net
  script:
    - mkdir -p $DEPLOY_ROOT
    - cd $DEPLOY_ROOT
    - echo COMPOSE_PROJECT_NAME=$CI_BUILD_REF_SLUG > .env
    - echo VIRTUAL_HOST=$CI_BUILD_REF_SLUG.gpcentre.net >> .env
    - echo GIT_BRANCH="$CI_BUILD_NAME" >> .env
    - docker-compose -p $CI_BUILD_REF_SLUG up -d
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_SLUG.$APPS_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  tags:
    - review-apps

stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
    DEPLOY_ROOT: /var/www/containers/$CI_BUILD_REF_SLUG-gpcentre-net
  script:
    # Removing any existing.env
    - cd $DEPLOY_ROOT
    - echo COMPOSE_PROJECT_NAME=$CI_BUILD_REF_SLUG > .env
    - echo VIRTUAL_HOST=$CI_BUILD_REF_SLUG.gpcentre.net >> .env
    - docker-compose -p $CI_BUILD_REF_SLUG down --remove-orphans
    - rm -rf $DEPLOY_ROOT
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  tags:
    - review-apps
    - shell

production:
  stage: production
  variables:
    DEPLOY_ROOT: /var/www/containers/gpcentre-net
  script:
    - mkdir -p $DEPLOY_ROOT
    - cd $DEPLOY_ROOT
    - cp -p /etc/docker/envs/gpcentre-net .env
    - docker-compose -p gpcentre.net up -d --remove-orphans
  tags:
    - shell
    - sfo2
  when: manual
  only:
    - master
