stages:
  - build
  - review
  - production

variables:
  DEPLOY_PATH: /var/docker/gpcentre.net
  APPS_DOMAIN: gpcentre.net
#  CI_DEBUG_TRACE: "true"

before_script:
    - echo COMPOSE_PROJECT_NAME=$CI_BUILD_REF_SLUG > .env
    - echo LETSENCRYPT_EMAIL=gp@gpcentre.net >> .env
    - echo WEBROOT=/var/www/html/public >> .env

build:
  tags:
    - php7
  stage: build
  script:
    - echo "Building the app"
    - docker build -t myproject/myapp .
    - docker tag gpcentre/gpcentre-net:latest \
      registry.gitlab.com/gpcentre/gpcentre-net:$CI_COMMIT_REF_NAME
    - docker push registry.gitlab.com/gpcentre/gpcentre-net:$CI_COMMIT_REF_NAME

review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Deploying Review env"
    - echo DOMAIN=$CI_BUILD_REF_SLUG.gpcentre.net >> .env
    - echo VIRTUAL_HOST=$CI_BUILD_REF_SLUG.gpcentre.net >> .env
    - echo LETSENCRYPT_HOST=$CI_BUILD_REF_SLUG.gpcentre.net >> .env
    - docker pull registry.gitlab.com/gpcentre/gpcentre-net:$CI_COMMIT_REF_NAME
    - docker stop review-$CI_COMMIT_REF_NAME || true
    - docker rm review-$CI_COMMIT_REF_NAME || true
    - docker run -d \
        -v /var/run/docker.sock:/var/run/docker.sock \
        --name review-$CI_COMMIT_REF_NAME \
        registry.gitlab.com/gpcentre/gpcentre-net:$CI_COMMIT_REF_NAME
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_SLUG.$APPS_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  tags:
    - shell
    - sfo2

stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - docker stop review-$CI_COMMIT_REF_NAME || true
    - docker rm review-$CI_COMMIT_REF_NAME || true
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  tags:
    - shell
    - sfo2
  except:
    - master

production:
  stage: production
  script:
    - echo DOMAIN=docker.gpcentre.net >> .env
    - echo VIRTUAL_HOST=docker.gpcentre.net >> .env
    - echo LETSENCRYPT_HOST=docker.gpcentre.net >> .env
    - docker stop gpcentre.net || true
    - docker rm gpcentre.net || true
    - docker run -d \
        -v /var/run/docker.sock:/var/run/docker.sock \
        --name gpcentre.net \
        registry.gitlab.com/gpcentre/gpcentre-net:$CI_COMMIT_REF_NAME
  tags:
    - shell
    - sfo2
  only:
    - master

#++ export DOCKER_DRIVER=overlay2
#++ DOCKER_DRIVER=overlay2
#++ export CI_PROJECT_DIR=/builds/gpcentre/gpcentre-net
#++ CI_PROJECT_DIR=/builds/gpcentre/gpcentre-net
#++ export CI_SERVER=yes
#++ CI_SERVER=yes
#++ mkdir -p /builds/gpcentre/gpcentre-net.tmp
#++ export CI_SERVER_TLS_CA_FILE=/builds/gpcentre/gpcentre-net.tmp/CI_SERVER_TLS_CA_FILE
#++ CI_SERVER_TLS_CA_FILE=/builds/gpcentre/gpcentre-net.tmp/CI_SERVER_TLS_CA_FILE
#++ export CI=true
#++ CI=true
#++ export GITLAB_CI=true
#++ GITLAB_CI=true
#++ export CI_SERVER_NAME=GitLab
#++ CI_SERVER_NAME=GitLab
#++ export CI_SERVER_VERSION=9.5.0-ee
#++ CI_SERVER_VERSION=9.5.0-ee
#++ export CI_SERVER_REVISION=36112e7
#++ CI_SERVER_REVISION=36112e7
#++ export CI_JOB_ID=30154423
#++ CI_JOB_ID=30154423
#++ export CI_JOB_NAME=review
#++ CI_JOB_NAME=review
#++ export CI_JOB_STAGE=review
#++ CI_JOB_STAGE=review
#++ export CI_JOB_TOKEN=xxxxxxxxxxxxxxxxxxxx
#++ CI_JOB_TOKEN=xxxxxxxxxxxxxxxxxxxx
#++ export CI_COMMIT_SHA=49ffa53e6d836736c63a6e22685059648ebd6847
#++ CI_COMMIT_SHA=49ffa53e6d836736c63a6e22685059648ebd6847
#++ export CI_COMMIT_REF_NAME=other/import-site
#++ CI_COMMIT_REF_NAME=other/import-site
#++ export CI_COMMIT_REF_SLUG=other-import-site
#++ CI_COMMIT_REF_SLUG=other-import-site
#++ export CI_REGISTRY_USER=gitlab-ci-token
#++ CI_REGISTRY_USER=gitlab-ci-token
#++ export CI_REGISTRY_PASSWORD=xxxxxxxxxxxxxxxxxxxx
#++ CI_REGISTRY_PASSWORD=xxxxxxxxxxxxxxxxxxxx
#++ export CI_REPOSITORY_URL=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/gpcentre/gpcentre-net.git
#++ CI_REPOSITORY_URL=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/gpcentre/gpcentre-net.git
#++ export CI_BUILD_ID=30154423
#++ CI_BUILD_ID=30154423
#++ export CI_BUILD_TOKEN=xxxxxxxxxxxxxxxxxxxx
#++ CI_BUILD_TOKEN=xxxxxxxxxxxxxxxxxxxx
#++ export CI_BUILD_REF=49ffa53e6d836736c63a6e22685059648ebd6847
#++ CI_BUILD_REF=49ffa53e6d836736c63a6e22685059648ebd6847
#++ export CI_BUILD_BEFORE_SHA=49ffa53e6d836736c63a6e22685059648ebd6847
#++ CI_BUILD_BEFORE_SHA=49ffa53e6d836736c63a6e22685059648ebd6847
#++ export CI_BUILD_REF_NAME=other/import-site
#++ CI_BUILD_REF_NAME=other/import-site
#++ export CI_BUILD_REF_SLUG=other-import-site
#++ CI_BUILD_REF_SLUG=other-import-site
#++ export CI_BUILD_NAME=review
#++ CI_BUILD_NAME=review
#++ export CI_BUILD_STAGE=review
#++ CI_BUILD_STAGE=review
#++ export CI_PROJECT_ID=2245543
#++ CI_PROJECT_ID=2245543
#++ export CI_PROJECT_NAME=gpcentre-net
#++ CI_PROJECT_NAME=gpcentre-net
#++ export CI_PROJECT_PATH=gpcentre/gpcentre-net
#++ CI_PROJECT_PATH=gpcentre/gpcentre-net
#++ export CI_PROJECT_PATH_SLUG=gpcentre-gpcentre-net
#++ CI_PROJECT_PATH_SLUG=gpcentre-gpcentre-net
#++ export CI_PROJECT_NAMESPACE=gpcentre
#++ CI_PROJECT_NAMESPACE=gpcentre
#++ export CI_PROJECT_URL=https://gitlab.com/gpcentre/gpcentre-net
#++ CI_PROJECT_URL=https://gitlab.com/gpcentre/gpcentre-net
#++ export CI_PIPELINE_ID=11128353
#++ CI_PIPELINE_ID=11128353
#++ export CI_CONFIG_PATH=.gitlab-ci.yml
#++ CI_CONFIG_PATH=.gitlab-ci.yml
#++ export CI_PIPELINE_SOURCE=push
#++ CI_PIPELINE_SOURCE=push
#++ export CI_RUNNER_ID=40788
#++ CI_RUNNER_ID=40788
#++ export CI_RUNNER_DESCRIPTION=shared-runners-manager-2.gitlab.com
#++ CI_RUNNER_DESCRIPTION=shared-runners-manager-2.gitlab.com
#++ export 'CI_RUNNER_TAGS=git-annex, mongo, postgres, mysql, ruby, linux, docker, shared'
#++ CI_RUNNER_TAGS='git-annex, mongo, postgres, mysql, ruby, linux, docker, shared'
#++ export CI_REGISTRY=registry.gitlab.com
#++ CI_REGISTRY=registry.gitlab.com
#++ export CI_REGISTRY_IMAGE=registry.gitlab.com/gpcentre/gpcentre-net
#++ CI_REGISTRY_IMAGE=registry.gitlab.com/gpcentre/gpcentre-net
#++ export APPS_DOMAIN=gpcentre.net
#++ APPS_DOMAIN=gpcentre.net
#++ export CI_DEBUG_TRACE=true
#++ CI_DEBUG_TRACE=true
#++ export GIT_EMAIL=gp@gpcentre.net
#++ GIT_EMAIL=gp@gpcentre.net
#++ export 'GIT_NAME=Philip G'
#++ GIT_NAME='Philip G'
#++ export COMPOSE_PROJECT_NAME=gpcentre-net
#++ COMPOSE_PROJECT_NAME=gpcentre-net
#++ export DOMAIN=www.gpcentre.net
#++ DOMAIN=www.gpcentre.net
#++ export WEBROOT=/var/www/html/public
#++ WEBROOT=/var/www/html/public
#++ export GIT_REPO=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/gpcentre/gpcentre-net.git
#++ GIT_REPO=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/gpcentre/gpcentre-net.git
#++ export GIT_USERNAME=gitlab-ci-token
#++ GIT_USERNAME=gitlab-ci-token
#++ export GIT_PERSONAL_TOKEN=xxxxxxxxxxxxxxxxxxxx
#++ GIT_PERSONAL_TOKEN=xxxxxxxxxxxxxxxxxxxx
#++ export GIT_BRANCH=other/import-site
#++ GIT_BRANCH=other/import-site
#++ export VIRTUAL_HOST=other-import-site.gpcentre.net
#++ VIRTUAL_HOST=other-import-site.gpcentre.net
#++ export GITLAB_USER_ID=915426
#++ GITLAB_USER_ID=915426
#++ export GITLAB_USER_EMAIL=gp@gpcentre.net
#++ GITLAB_USER_EMAIL=gp@gpcentre.net
#++ export CI_ENVIRONMENT_NAME=review/other/import-site
#++ CI_ENVIRONMENT_NAME=review/other/import-site
#++ export CI_ENVIRONMENT_SLUG=review-other-impo-bfyicn
#++ CI_ENVIRONMENT_SLUG=review-other-impo-bfyicn
#++ export CI_ENVIRONMENT_URL=http://other-import-site.gpcentre.net
#++ CI_ENVIRONMENT_URL=http://other-import-site.gpcentre.net
#++ cd /builds/gpcentre/gpcentre-net