version: '2'
services:
  gpc:
    image: gpcentre/php71-fpm-nginx:latest
    env_file: /etc/docker/envs/gpcentre-net.env
    environment:
      WEBROOT: /var/www/public
      DOMAIN: www.gpcentre.net
      GIT_EMAIL: gp@gpcentre.net
      VIRTUAL_HOST: localhost,*.gpcentre.net,138.68.11.157
    external_links:
      - mariadb-node1:mariadb
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - "$WWWW_ROOT:/var/www"
networks:
  default:
    external:
      name: gpcentre_default
