version: '2'
services:
   gpcentre-net:
    image: nginx:latest
    environment:
      WORKDIR: /etc/nginx
      VIRTUAL_HOST: localhost,*.gpcentre.net,138.68.11.157
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - "$VAR_ROOT/www/gpcentre-net:/var/www/gpcentre-net"
      - "$VAR_ROOT/lib/php-fpm:/var/lib/php-fpm"
    replicas: 3
networks:
  default:
    external:
      name: gpcentre_default
