version: '2'
services:
  gpc:
    image: gpcentre/php71-fpm-nginx:latest
    env_file: .env
    environment:
      WEBROOT: /var/www/public
    external_links:
      - mariadb-node1:mariadb
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - ./src:/var/www
    restart: always
networks:
  default:
    external:
      name: gpcentre_default
