version: '3'
services:
  www:
    build: .
    env_file: .env
    external_links:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  default:
    external:
      name: gpcentre_default