version: '2'
services:
  gpc:
    image: gpcentre/php71-fpm-nginx:latest
    env_file: /etc/docker/envs/gpcentre-net.env
    environment:
      COMPOSE_PROJECT_NAME: gpcentre-net
      DOMAIN: www.gpcentre.net
      GIT_EMAIL: gp@gpcentre.net
      VIRTUAL_HOST: localhost,*.gpcentre.net,138.68.11.157
      WEBROOT: /var/www/public
    external_links:
      - mariadb-node1:mariadb
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - ./src:/var/www
networks:
  default:
    external:
      name: gpcentre_default
