version: '3'
services:
  gpc:
    image: richarvey/nginx-php-fpm:latest
    env_file: .env
    environment:
      - GIT_EMAIL=gp@gpcentre.net
      - GIT_NAME="Philip G"
      - GIT_USERNAME=guice
      - GIT_REPO=gitlab.com/gpcentre/gpcentre-net.git
      - WEBROOT=/var/www/html/public
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - .:/var/www/html
networks:
  default:
    external:
      name: gpcentre_default